name: Flutter CI/CD

on:
  push:
    branches: [main] # Запускать pipeline только при пуше в ветку main
    paths:
      - 'client-giftly/**' # Учитывать изменения только в подмодуле client-giftly

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ----------------------
      # 1. Подготовка
      # ----------------------
      - name: 🏗 Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: true # Инициализация подмодулей

      - name: 🛠 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # Убедитесь, что версия существует
          channel: 'stable'
          cache: true
          cache-key: ${{ runner.os }}-flutter-${{ hashFiles('client-giftly/pubspec.lock') }}

      # Переход в папку подмодуля
      - name: 📂 Navigate to submodule directory
        run: cd client-giftly

      # ----------------------
      # 2. Тесты и проверки
      # ----------------------
      - name: 📦 Install dependencies
        run: flutter pub get
        working-directory: client-giftly # Указываем рабочую директорию

      - name: 🧪 Run unit tests
        run: flutter test
        working-directory: client-giftly

      - name: 🔍 Static analysis
        run: flutter analyze
        working-directory: client-giftly

      - name: 🖌 Check formatting
        run: dart format --set-exit-if-changed .
        working-directory: client-giftly

      - name: 🧩 Run widget tests
        run: flutter test test/widget_test.dart
        working-directory: client-giftly
